/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa1_Presentacion;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Claudio
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setExtendedState (frmMenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuProductos = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuFacturas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnuGastos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mnuCierre = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Personas");

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuClientes);

        mnuProveedores.setText("Proveedores");
        mnuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProveedoresActionPerformed(evt);
            }
        });
        jMenu2.add(mnuProveedores);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("Productos");

        mnuProductos.setText("Registrar Producto");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        jMenu3.add(mnuProductos);

        jMenuBar1.add(jMenu3);

        jMenu6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setText("Facturar");

        mnuFacturas.setText("Nueva Factura");
        mnuFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturasActionPerformed(evt);
            }
        });
        jMenu6.add(mnuFacturas);

        jMenuBar1.add(jMenu6);

        jMenu7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setText("Gastos");

        mnuGastos.setText("Registrar Gasto");
        mnuGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGastosActionPerformed(evt);
            }
        });
        jMenu7.add(mnuGastos);

        jMenuBar1.add(jMenu7);

        jMenu8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu8.setText("Cierre");

        mnuCierre.setText("Registra Cierre del Día");
        jMenu8.add(mnuCierre);

        jMenuBar1.add(jMenu8);

        mnuSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuSalir.setText("Salir");
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
         frmClientes frm = new frmClientes();
        escritorio.add(frm);
        
        Dimension sizeContenedor = escritorio.getSize();
        
        Dimension sizeFrmClientes = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth() - (int)sizeFrmClientes.getWidth())/2, ((int)sizeContenedor.getHeight() - (int)sizeFrmClientes.getHeight())/2);

        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed
   
    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
         frmProductos frm = null;
        try {
            frm = new frmProductos();
        } catch (Exception ex) {
            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        escritorio.add(frm);
        
        Dimension sizeContenedor = escritorio.getSize();
        
        Dimension sizeFrmProductos = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth() - (int)sizeFrmProductos.getWidth())/2, ((int)sizeContenedor.getHeight() - (int)sizeFrmProductos.getHeight())/2);

        frm.toFront();
        frm.setVisible(true);
        
        
        
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mnuFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturasActionPerformed
         frmFacturas frm = new frmFacturas();
         
        escritorio.add(frm);
        
        Dimension sizeContenedor = escritorio.getSize();
        
        Dimension sizeFrmFacturas = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth() - (int)sizeFrmFacturas.getWidth())/2, ((int)sizeContenedor.getHeight() - (int)sizeFrmFacturas.getHeight())/2);

        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuFacturasActionPerformed

    private void mnuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProveedoresActionPerformed
          frmProveedores frm = new frmProveedores();
        escritorio.add(frm);
        
        Dimension sizeContenedor = escritorio.getSize();
        
        Dimension sizeFrmClientes = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth() - (int)sizeFrmClientes.getWidth())/2, ((int)sizeContenedor.getHeight() - (int)sizeFrmClientes.getHeight())/2);

        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuProveedoresActionPerformed

    private void mnuGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGastosActionPerformed
        frmGasto frm = new frmGasto();
        escritorio.add(frm);
        
        Dimension sizeContenedor = escritorio.getSize();
        
        Dimension sizeFrmClientes = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth() - (int)sizeFrmClientes.getWidth())/2, ((int)sizeContenedor.getHeight() - (int)sizeFrmClientes.getHeight())/2);

        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCierre;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuFacturas;
    private javax.swing.JMenuItem mnuGastos;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuProveedores;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
